<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"  ng-click="toggle.cinsiyet=!toggle.cinsiyet;filtre.cinsiyet=''">Cinsiyet</a></li>
                <li><a href="#"  ng-click="toggle.yas=!toggle.yas;filtre.yas=''">Yaş</a></li>
                <li><a href="#"  ng-click="toggle.boy=!toggle.boy;filtre.boy=''">Boy</a></li>
                <li><a href="#"  ng-click="toggle.kilo=!toggle.kilo;filtre.kilo=''">Kilo</a></li>
                <li><a href="#"  ng-click="toggle.kan_grubu=!toggle.kan_grubu;filtre.kan_grubu=''">Kan Grubu</a></li>
                <li><a href="#"  ng-click="toggle.medeni_hal=!toggle.medeni_hal;filtre.medeni_hal=''">Medeni Hal</a></li>
                <li><a href="#"  ng-click="toggle.kadro=!toggle.kadro;filtre.kadro=''">Kadro</a></li>
                <li><a href="#"  ng-click="toggle.alkol_kullanimi=!toggle.alkol_kullanimi;filtre.alkol_kullanimi=''">Alkol K.</a></li>
                <li><a href="#"  ng-click="toggle.sigara_kullanimi=!toggle.sigara_kullanimi;filtre.sigara_kullanimi=''">Sigara K.</a></li>
                <li><a href="#"  ng-click="toggle.siklik=!toggle.tekrar;filtre.tekrar=''">Tekrar</a></li>
                <li><a href="#"  ng-click="toggle.sekil=!toggle.sekil;filtre.sekil=''">Şekil</a></li>
                <li><a href="#"  ng-click="toggle.sure=!toggle.sure;filtre.sure=''">Süre</a></li>
                <li><a href="#"  ng-click="toggle.yer=!toggle.yer;filtre.yer=''">Yer</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li>
                    <a class="btn btn-primary" ng-click="filtrele()">Filtrele</a>
                </li>
                <li ng-if="toggle.cinsiyet">

                    <labe>Cinsiyet</labe>
                    <select class="form-control" ng-model="filtre.cinsiyet">
                        <option value="">-- Seçim Yapınız --</option>
                        <option ng-repeat="item in selectData.cinsiyet" value="{{item.cinsiyet}}">{{item.cinsiyet}}</option>
                    </select>
                </li>
                <li ng-if="toggle.yas">
                    <labe>Yaş</labe>
                    <select class="form-control" ng-model="filtre.yas">
                        <option value="">-- Seçim Yapınız --</option>
                        <option ng-repeat="item in selectData.yas" value="{{item.yas}}">{{item.yas}}</option>
                    </select>
                </li>
                <li ng-if="toggle.boy">
                    <labe>Boy</labe>
                    <select class="form-control" ng-model="filtre.boy">
                        <option value="">-- Seçim Yapınız --</option>
                        <option ng-repeat="item in selectData.boy" value="{{item.boy}}">{{item.boy}}</option>
                    </select>
                </li>
                <li ng-if="toggle.kilo">
                    <labe>Kilo</labe>
                    <select class="form-control" ng-model="filtre.kilo">
                        <option value="">-- Seçim Yapınız --</option>
                        <option ng-repeat="item in selectData.kilo" value="{{item.kilo}}">{{item.kilo}}</option>
                    </select>
                </li>
                <li ng-if="toggle.kan_grubu">
                    <labe>Kan Grubu</labe>
                    <select class="form-control" ng-model="filtre.kan_grubu">
                        <option value="">-- Seçim Yapınız --</option>
                        <option ng-repeat="item in selectData.kan_grubu" value="{{item.kan_grubu}}">{{item.kan_grubu}}</option>
                    </select>
                </li>
                <li ng-if="toggle.medeni_hal">
                    <labe>Medeni Hal</labe>
                    <select class="form-control" ng-model="filtre.medeni_hal">
                        <option value="">-- Seçim Yapınız --</option>
                        <option ng-repeat="item in selectData.cinsiyet" value="{{item.cinsiyet}}">{{item.cinsiyet}}</option>
                    </select>
                </li>
                <li ng-if="toggle.kadro">
                    <labe>Kadro</labe>
                    <select class="form-control" ng-model="filtre.kadro">
                        <option value="">-- Seçim Yapınız --</option>
                        <option ng-repeat="item in selectData.kadro" value="{{item.kadro}}">{{item.kadro}}</option>
                    </select>
                </li>
                <li ng-if="toggle.alkol_kullanimi">
                    <labe>Alkol Kullanımı</labe>
                    <select class="form-control" ng-model="filtre.alkol_kullanimi">
                        <option ng-repeat="item in selectData.alkol_kullanimi" value="{{item.alkol_kullanimi}}">{{item.alkol_kullanimi}}</option>
                    </select>
                </li>
                <li ng-if="toggle.sigara_kullanimi">
                    <labe>Sigara Kullanımı</labe>
                    <select class="form-control" ng-model="filtre.sigara_kullanimi">
                        <option value="">-- Seçim Yapınız --</option>
                        <option ng-repeat="item in selectData.sigara_kullanimi" value="{{item.sigara_kullanimi}}">{{item.sigara_kullanimi}}</option>
                    </select>
                </li>
                <li ng-if="toggle.tekrar">
                    <labe>Sıklık</labe>
                    <select class="form-control" ng-model="filtre.tekrar">
                        <option value="">-- Seçim Yapınız --</option>
                        <option ng-repeat="item in selectData.tekrar" value="{{item.tekrar}}">{{item.tekrar}}</option>
                    </select>
                </li>
                <li ng-if="toggle.sekil">
                    <labe>Şekil</labe>
                    <select class="form-control" ng-model="filtre.sekil">
                        <option value="">-- Seçim Yapınız --</option>
                        <option ng-repeat="item in selectData.sekil" value="{{item.sekil}}">{{item.sekil}}</option>
                    </select>
                </li>
                <li ng-if="toggle.sure">
                    <labe>Süre</labe>
                    <select class="form-control" ng-model="filtre.sure">
                        <option value="">-- Seçim Yapınız --</option>
                        <option ng-repeat="item in selectData.sure" value="{{item.sure}}">{{item.sure}}</option>
                    </select>
                </li>
                <li ng-if="toggle.yer">
                    <labe>Yer</labe>
                    <select class="form-control" ng-model="filtre.yer">
                        <option value="">-- Seçim Yapınız --</option>
                        <option ng-repeat="item in selectData.yer" value="{{item.yer}}">{{item.yer}}</option>
                    </select>
                </li>
            </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">Sonuç</h1>

            <svg width="960" height="3000"></svg>
            <div class="row">
                <div class="col-md-6">
                    <h2>Frekans Öğeleri</h2>
                    <div ng-bind-html="FreqItemsets| to_trusted"></div>
                </div>
                <div class="col-md-6">
                    <h2>Birliktelik Kuralları</h2>
                    <div ng-bind-html="AssociationRules| to_trusted"></div>
                </div>


            </div>
        </div>

    </div>
</div>

<style>

    .node circle {
        fill: #999;
    }

    .node text {
        font: 10px sans-serif;
    }

    .node--internal circle {
        fill: #555;
    }

    .node--internal text {
        text-shadow: 0 1px 0 #fff, 0 -1px 0 #fff, 1px 0 0 #fff, -1px 0 0 #fff;
    }

    .link {
        fill: none;
        stroke: #555;
        stroke-opacity: 0.4;
        stroke-width: 1.5px;
    }

</style>
